#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Write the 'Data sources' section of README.md from the provenance table.

The public repository redistributes derived matrices built from other people's data. The
licence file states the terms; this section tells a reader whom to cite. It is generated so
that the accession list cannot drift from results/dataset_provenance.tsv, and it is
idempotent: the block between the two markers is replaced on every run.

    python scripts/readme_data_sources.py
"""
import os
import sys

import pandas as pd

BEGIN = '<!-- BEGIN DATA SOURCES (generated by scripts/readme_data_sources.py) -->'
END = '<!-- END DATA SOURCES -->'

# Accessions the paper uses that the provenance table does not carry a publication for:
# cite the depositing study named on the accession page.
EXTRA = {
    'GEO, kidney': ['GSE294519', 'GSE162830', 'GSE5406 (heart)'],
    'GEO, liver (MASH)': ['GSE89632', 'GSE48452', 'GSE162694', 'GSE126848', 'GSE83452',
                          'GSE66676', 'GSE63067', 'GSE24807'],
    'GEO, colon (ulcerative colitis)': ['GSE75214', 'GSE87466', 'GSE179285', 'GSE11223',
                                        'GSE47908', 'GSE38713', 'GSE53306', 'GSE16879',
                                        'GSE48958', 'GSE13367'],
}
OTHER = """- **Kidney Precision Medicine Project** single-nucleus atlas, https://atlas.kpmp.org/ (open-access,
  de-identified portion only). Required acknowledgement: *The results reported here are in whole
  or in part based upon data generated by the Kidney Precision Medicine Project
  (https://www.kpmp.org). The KPMP study is supported by the National Institute of Diabetes and
  Digestive and Kidney Diseases.* Cite El-Achkar et al., Physiol Genomics 2021 (PMID 33197228)
  and Lake et al., Nature 2023;619:585-594.
- **Mendeley Data 83k89shdx5** (SOMAscan proteomics of kidney cortex biopsies): cite
  Hirohama et al., 2023 (the depositing study; details in the manuscript reference list).
- **PRIDE PXD041884** (LC-MS/MS of FFPE kidney cortex): cite the depositing study
  (Schwab et al., 2024; details in the manuscript reference list).
- **GWAS Catalog GCST90179152**: cite the GWAS Catalog and the source study on the accession page.
- **Metabolomics Workbench** ST003255, ST001411, ST000691, ST004483, ST004442, ST002145:
  cite Metabolomics Workbench (Sud et al., Nucleic Acids Res 2016) and the study named on each
  project page."""


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)
    d = pd.read_csv('results/dataset_provenance.tsv', sep='\t', dtype=str).fillna('')
    lines = ['## Data sources: please cite the original studies', '',
             'Every matrix in `data/processed/` is derived from public data that other groups',
             'generated. `LICENSE-DATA.md` states the terms; this list says whom to credit. Cite',
             'the original study of each accession you use, not only this repository.', '',
             '| accession | repository | original study | PMID |', '|---|---|---|---|']
    for _, r in d.iterrows():
        if not r['citation']:
            continue
        pm = '; '.join(r['pmid'].split(';')) if r['pmid'] else ''
        lines.append('| %s | %s | %s | %s |' % (r['accession'], r['repository'].replace('NCBI ', ''),
                                                 r['citation'], pm))
    lines.append('')
    lines.append('Accessions without a row above (cite the depositing study named on each accession page):')
    lines.append('')
    for k, v in EXTRA.items():
        lines.append('- **%s**: %s' % (k, ', '.join(v)))
    lines.append(OTHER)
    lines.append('')
    lines.append('The full provenance table, with platforms, sample counts and titles, is')
    lines.append('`results/dataset_provenance.tsv`.')
    block = BEGIN + '\n' + '\n'.join(lines) + '\n' + END

    p = 'README.md'
    s = open(p, encoding='utf-8').read()
    if BEGIN in s and END in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + block + s[j:]
    else:
        anchor = '## Data\n'
        assert s.count(anchor) == 1, 'README anchor "## Data" not found once'
        s = s.replace(anchor, block + '\n\n' + anchor)
    open(p, 'w', encoding='utf-8').write(s)
    print('README.md: data-sources section written (%d cited accessions)' % (d['citation'] != '').sum(),
          file=sys.stderr)


if __name__ == '__main__':
    main()
